from __future__ import annotations

from collections.abc import Iterable, Iterator, Mapping, Sequence
from typing import Any, Literal, Self, overload

from . import types as types

class ArrowException(Exception): ...  # noqa: N818
class ArrowNotImplementedError(ArrowException, NotImplementedError): ...

class DataType:
    @property
    def num_fields(self) -> int: ...
    @property
    def num_buffers(self) -> int: ...
    def field(self, index: int) -> Field: ...

class Int8Type(DataType): ...
class StringType(DataType): ...
class LargeStringType(DataType): ...
class StringViewType(DataType): ...
class BinaryViewType(DataType): ...

class DictionaryType(DataType):
    @property
    def ordered(self) -> bool: ...

class DurationType(DataType):
    @property
    def unit(self) -> Literal["s", "ms", "us", "ns"]: ...

class Field:
    @property
    def name(self) -> str: ...
    @property
    def type(self) -> DataType: ...

class StructType(DataType):
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, index: int) -> Field: ...
    @overload
    def __getitem__(self, index: str) -> Field: ...
    def field(self, index: int | str) -> Field: ...

class Schema:
    @property
    def names(self) -> list[str]: ...
    def __iter__(self) -> Iterator[Field]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Field: ...
    def equals(self, other: Schema, check_metadata: bool = False) -> bool: ...
    def field(self, index: int | str) -> Field: ...

class Scalar:
    @property
    def is_valid(self) -> bool: ...
    @property
    def type(self) -> DataType: ...
    def as_py(self) -> Any: ...

class DictionaryScalar(Scalar):
    @property
    def value(self) -> Scalar: ...

class JsonScalar(Scalar):
    @property
    def value(self) -> Scalar | None: ...

class UuidScalar(Scalar): ...

class Buffer:
    def __len__(self) -> int: ...
    def slice(self, offset: int = 0, length: int | None = None) -> Self: ...
    def to_pybytes(self) -> bytes: ...

class BinaryScalar(Scalar):
    def as_buffer(self) -> Buffer: ...

class LargeBinaryScalar(Scalar):
    def as_buffer(self) -> Buffer: ...

class FixedSizeBinaryScalar(Scalar):
    def as_buffer(self) -> Buffer: ...

class BinaryViewScalar(Scalar):
    def as_buffer(self) -> Buffer: ...

class StringScalar(Scalar):
    def as_buffer(self) -> Buffer: ...

class LargeStringScalar(Scalar):
    def as_buffer(self) -> Buffer: ...

class StringViewScalar(Scalar):
    def as_buffer(self) -> Buffer: ...

class ListScalar(Scalar):
    @property
    def values(self) -> Array | None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Scalar: ...

class LargeListScalar(Scalar):
    @property
    def values(self) -> Array | None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Scalar: ...

class FixedSizeListScalar(Scalar):
    @property
    def values(self) -> Array | None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Scalar: ...

class DurationScalar(Scalar):
    @property
    def value(self) -> int | None: ...

class StructScalar(Scalar):
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, key: int) -> Scalar: ...
    @overload
    def __getitem__(self, key: str) -> Scalar: ...

class MapScalar(Scalar):
    @property
    def values(self) -> StructArray | None: ...
    def __len__(self) -> int: ...

class Array:
    @staticmethod
    def from_buffers(
        type: DataType,
        length: int,
        buffers: Sequence[Buffer | None],
        null_count: int = -1,
        offset: int = 0,
        children: Sequence[Array] | None = None,
    ) -> Array: ...
    @property
    def nbytes(self) -> int: ...
    def buffers(self) -> list[Buffer | None]: ...
    def slice(self, offset: int = 0, length: int | None = None) -> Array: ...
    @property
    def type(self) -> DataType: ...
    @property
    def null_count(self) -> int: ...
    def __iter__(self) -> Iterator[Scalar]: ...
    def __getitem__(self, index: int) -> Scalar: ...
    def __len__(self) -> int: ...
    def take(self, indices: Array | Iterable[int]) -> Array: ...

class DictionaryArray(Array):
    def dictionary_decode(self) -> Array: ...
    @staticmethod
    def from_arrays(
        indices: Array,
        dictionary: Array,
        mask: Array | None = None,
        ordered: bool = False,
        from_pandas: bool = False,
        safe: bool = True,
        memory_pool: MemoryPool | None = None,
    ) -> DictionaryArray: ...
    @property
    def type(self) -> DictionaryType: ...
    @property
    def indices(self) -> Array: ...
    @property
    def dictionary(self) -> Array: ...

class ListArray(Array):
    @staticmethod
    def from_arrays(
        offsets: Array,
        values: Array,
        type: DataType | None = None,
        pool: MemoryPool | None = None,
        mask: Array | None = None,
    ) -> ListArray: ...
    @property
    def values(self) -> Array: ...

class LargeListArray(Array):
    @property
    def values(self) -> Array: ...

class FixedSizeListArray(Array):
    @property
    def values(self) -> Array: ...

class MapArray(Array):
    @property
    def values(self) -> StructArray: ...

class StructArray(Array):
    def field(self, index: int | str) -> Array: ...

class ChunkedArray:
    @property
    def type(self) -> DataType: ...
    @property
    def null_count(self) -> int: ...
    @property
    def num_chunks(self) -> int: ...
    def __iter__(self) -> Iterator[Scalar]: ...
    def __getitem__(self, index: int) -> Scalar: ...
    def __len__(self) -> int: ...
    def take(self, indices: Array | Iterable[int]) -> ChunkedArray: ...
    def combine_chunks(self) -> Array: ...

class Table:
    @classmethod
    def from_batches(
        cls, batches: Iterable[RecordBatch], schema: Schema | None = None
    ) -> Table: ...
    @property
    def column_names(self) -> list[str]: ...
    @property
    def columns(self) -> list[ChunkedArray]: ...
    @property
    def num_rows(self) -> int: ...
    @property
    def num_columns(self) -> int: ...
    @property
    def schema(self) -> Schema: ...
    @property
    def nbytes(self) -> int: ...
    def column(self, i: int | str) -> ChunkedArray: ...
    def equals(self, other: Table, check_metadata: bool = False) -> bool: ...
    def get_total_buffer_size(self) -> int: ...
    def slice(self, offset: int = 0, length: int | None = None) -> Table: ...
    def to_batches(self, max_chunksize: int | None = None) -> list[RecordBatch]: ...

class RecordBatch:
    @classmethod
    def from_arrays(
        cls,
        arrays: Sequence[Array],
        names: Sequence[str] | None = None,
        schema: Schema | None = None,
    ) -> RecordBatch: ...
    @property
    def schema(self) -> Schema: ...
    @property
    def num_rows(self) -> int: ...
    @property
    def nbytes(self) -> int: ...
    def column(self, i: int) -> Array: ...
    def slice(self, offset: int = 0, length: int | None = None) -> RecordBatch: ...
    def take(self, indices: Array | Iterable[int]) -> RecordBatch: ...

class RecordBatchReader:
    @staticmethod
    def from_batches(
        schema: Schema, batches: Iterable[RecordBatch]
    ) -> RecordBatchReader: ...
    @property
    def schema(self) -> Schema: ...
    def read_next_batch(self) -> RecordBatch: ...
    def close(self) -> None: ...

class NativeFile: ...

class MemoryPool:
    def bytes_allocated(self) -> int: ...
    def max_memory(self) -> int | None: ...

def default_memory_pool() -> MemoryPool: ...
def proxy_memory_pool(parent: MemoryPool) -> MemoryPool: ...
def set_memory_pool(pool: MemoryPool) -> None: ...
def int64() -> DataType: ...
def timestamp(
    unit: Literal["s", "ms", "us", "ns"], tz: str | None = None
) -> DataType: ...
def int8() -> Int8Type: ...
def string() -> StringType: ...
def large_string() -> LargeStringType: ...
def string_view() -> StringViewType: ...
def binary_view() -> BinaryViewType: ...
def json_(storage_type: DataType = ...) -> DataType: ...
def uuid() -> DataType: ...
def list_(value_type: DataType | Field, list_size: int = -1) -> DataType: ...
def decimal256(precision: int, scale: int = 0) -> DataType: ...
def list_view(value_type: DataType | Field) -> DataType: ...
def large_list(value_type: DataType | Field) -> DataType: ...
def map_(
    key_type: DataType | Field, item_type: DataType | Field, keys_sorted: bool = False
) -> DataType: ...
def field(
    name: str,
    type: DataType,
    nullable: bool = True,
    metadata: Mapping[Any, Any] | None = None,
) -> Field: ...
def schema(
    fields: Iterable[Field | tuple[str, DataType]],
    metadata: Mapping[Any, Any] | None = None,
) -> Schema: ...
def duration(unit: Literal["s", "ms", "us", "ns"]) -> DurationType: ...
def month_day_nano_interval() -> DataType: ...
def scalar(
    value: Any,
    type: DataType | None = None,
    *,
    from_pandas: bool | None = None,
    memory_pool: MemoryPool | None = None,
) -> Scalar: ...
def dictionary(
    index_type: DataType, value_type: DataType, ordered: bool = False
) -> DictionaryType: ...
def struct(
    fields: Iterable[Field | tuple[str, DataType]] | Mapping[str, DataType],
) -> StructType: ...
def array(
    obj: Iterable[Any],
    type: DataType | None = None,
    mask: Array | None = None,
    size: int | None = None,
    from_pandas: bool | None = None,
    safe: bool = True,
    memory_pool: Any | None = None,
) -> Array: ...
def chunked_array(
    arrays: Iterable[Array | Iterable[Any]], type: DataType | None = None
) -> ChunkedArray: ...
def table(
    data: Mapping[str, Array | ChunkedArray | Sequence[Any]],
    names: Sequence[str] | None = None,
    schema: Schema | None = None,
    metadata: Mapping[Any, Any] | None = None,
    nthreads: int | None = None,
) -> Table: ...
