from __future__ import annotations

from collections.abc import Iterable, Iterator, Mapping, Sequence
from typing import Any, Literal, Self, overload

from . import types as types

class ArrowException(Exception): ...  # noqa: N818
class DataType: ...
class Int8Type(DataType): ...
class StringType(DataType): ...
class LargeStringType(DataType): ...
class StringViewType(DataType): ...
class DictionaryType(DataType): ...

class DurationType(DataType):
    @property
    def unit(self) -> Literal["s", "ms", "us", "ns"]: ...

class Field:
    @property
    def name(self) -> str: ...
    @property
    def type(self) -> DataType: ...

class StructType(DataType):
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, index: int) -> Field: ...
    @overload
    def __getitem__(self, index: str) -> Field: ...
    def field(self, index: int | str) -> Field: ...

class Schema:
    def __iter__(self) -> Iterator[Field]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Field: ...

class Scalar:
    @property
    def is_valid(self) -> bool: ...
    @property
    def type(self) -> DataType: ...
    def as_py(self) -> Any: ...

class Buffer:
    def __len__(self) -> int: ...
    def slice(self, offset: int = 0, length: int | None = None) -> Self: ...
    def to_pybytes(self) -> bytes: ...

class BinaryScalar(Scalar):
    def as_buffer(self) -> Buffer: ...

class LargeBinaryScalar(Scalar):
    def as_buffer(self) -> Buffer: ...

class FixedSizeBinaryScalar(Scalar):
    def as_buffer(self) -> Buffer: ...

class StringScalar(Scalar):
    def as_buffer(self) -> Buffer: ...

class LargeStringScalar(Scalar):
    def as_buffer(self) -> Buffer: ...

class StringViewScalar(Scalar):
    def as_buffer(self) -> Buffer: ...

class ListScalar(Scalar):
    @property
    def values(self) -> Array | None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Scalar: ...

class LargeListScalar(Scalar):
    @property
    def values(self) -> Array | None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Scalar: ...

class FixedSizeListScalar(Scalar):
    @property
    def values(self) -> Array | None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Scalar: ...

class DurationScalar(Scalar):
    @property
    def value(self) -> int | None: ...

class StructScalar(Scalar):
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, key: int) -> Scalar: ...
    @overload
    def __getitem__(self, key: str) -> Scalar: ...

class MapScalar(Scalar):
    @property
    def values(self) -> StructArray | None: ...
    def __len__(self) -> int: ...

class Array:
    @property
    def type(self) -> DataType: ...
    @property
    def null_count(self) -> int: ...
    def __iter__(self) -> Iterator[Scalar]: ...
    def __getitem__(self, index: int) -> Scalar: ...
    def __len__(self) -> int: ...
    def take(self, indices: Array | Iterable[int]) -> Array: ...

class StructArray(Array):
    def field(self, index: int | str) -> Array: ...

class ChunkedArray:
    @property
    def type(self) -> DataType: ...
    @property
    def null_count(self) -> int: ...
    def __iter__(self) -> Iterator[Scalar]: ...
    def __getitem__(self, index: int) -> Scalar: ...
    def __len__(self) -> int: ...
    def take(self, indices: Array | Iterable[int]) -> ChunkedArray: ...
    def combine_chunks(self) -> Array: ...

class Table:
    @property
    def column_names(self) -> list[str]: ...
    @property
    def columns(self) -> list[ChunkedArray]: ...
    @property
    def num_rows(self) -> int: ...
    @property
    def num_columns(self) -> int: ...
    @property
    def schema(self) -> Schema: ...
    @property
    def nbytes(self) -> int: ...
    def column(self, i: int | str) -> ChunkedArray: ...

class RecordBatch: ...
class NativeFile: ...
class MemoryPool: ...

def int64() -> DataType: ...
def int8() -> Int8Type: ...
def string() -> StringType: ...
def duration(unit: Literal["s", "ms", "us", "ns"]) -> DurationType: ...
def month_day_nano_interval() -> DataType: ...
def scalar(
    value: Any,
    type: DataType | None = None,
    *,
    from_pandas: bool | None = None,
    memory_pool: MemoryPool | None = None,
) -> Scalar: ...
def dictionary(
    index_type: DataType, value_type: DataType, ordered: bool = False
) -> DictionaryType: ...
def struct(
    fields: Iterable[Field | tuple[str, DataType]] | Mapping[str, DataType],
) -> StructType: ...
def array(
    obj: Iterable[Any],
    type: DataType | None = None,
    mask: Array | None = None,
    size: int | None = None,
    from_pandas: bool | None = None,
    safe: bool = True,
    memory_pool: Any | None = None,
) -> Array: ...
def table(
    data: Mapping[str, Array | ChunkedArray | Sequence[Any]],
    names: Sequence[str] | None = None,
    schema: Schema | None = None,
    metadata: Mapping[Any, Any] | None = None,
    nthreads: int | None = None,
) -> Table: ...
