from __future__ import annotations

from collections.abc import Iterable, Iterator, Mapping, Sequence
from typing import Any

from . import types as types

class ArrowException(Exception): ...  # noqa: N818
class DataType: ...

class Field:
    @property
    def name(self) -> str: ...
    @property
    def type(self) -> DataType: ...

class Schema:
    def __iter__(self) -> Iterator[Field]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Field: ...

class Scalar:
    @property
    def is_valid(self) -> bool: ...
    @property
    def type(self) -> DataType: ...
    def as_py(self) -> Any: ...

class Array:
    @property
    def type(self) -> DataType: ...
    def __iter__(self) -> Iterator[Scalar]: ...
    def __getitem__(self, index: int) -> Scalar: ...
    def __len__(self) -> int: ...
    def take(self, indices: Array | Iterable[int]) -> Array: ...

class ChunkedArray:
    @property
    def type(self) -> DataType: ...
    def __iter__(self) -> Iterator[Scalar]: ...
    def __getitem__(self, index: int) -> Scalar: ...
    def __len__(self) -> int: ...
    def take(self, indices: Array | Iterable[int]) -> ChunkedArray: ...
    def combine_chunks(self) -> Array: ...

class Table:
    @property
    def column_names(self) -> list[str]: ...
    @property
    def columns(self) -> list[ChunkedArray]: ...
    @property
    def num_rows(self) -> int: ...
    @property
    def num_columns(self) -> int: ...
    @property
    def schema(self) -> Schema: ...
    @property
    def nbytes(self) -> int: ...
    def column(self, i: int | str) -> ChunkedArray: ...

class RecordBatch: ...
class NativeFile: ...

def int64() -> DataType: ...
def array(
    obj: Iterable[Any],
    type: DataType | None = None,
    mask: Array | None = None,
    size: int | None = None,
    from_pandas: bool | None = None,
    safe: bool = True,
    memory_pool: Any | None = None,
) -> Array: ...
def table(
    data: Mapping[str, Array | ChunkedArray | Sequence[Any]],
    names: Sequence[str] | None = None,
    schema: Schema | None = None,
    metadata: Mapping[Any, Any] | None = None,
    nthreads: int | None = None,
) -> Table: ...
