from __future__ import annotations

from . import DataType

def is_integer(data_type: DataType) -> bool: ...
def is_floating(data_type: DataType) -> bool: ...
def is_decimal(data_type: DataType) -> bool: ...
def is_boolean(data_type: DataType) -> bool: ...
def is_temporal(data_type: DataType) -> bool: ...
def is_binary(data_type: DataType) -> bool: ...
def is_large_binary(data_type: DataType) -> bool: ...
def is_fixed_size_binary(data_type: DataType) -> bool: ...
def is_list(data_type: DataType) -> bool: ...
def is_large_list(data_type: DataType) -> bool: ...
def is_fixed_size_list(data_type: DataType) -> bool: ...
def is_struct(data_type: DataType) -> bool: ...
def is_map(data_type: DataType) -> bool: ...
def is_null(data_type: DataType) -> bool: ...
